---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mutating-webhook
  namespace: admission-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-list
  namespace: admission-controller
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-list
  namespace: admission-controller
subjects:
- kind: ServiceAccount
  name: mutating-webhook
  namespace: admission-controller
roleRef:
  kind: ClusterRole
  name: namespace-list
  apiGroup: rbac.authorization.k8s.io