---
apiVersion: v1
kind: Pod
metadata:
  generateName: nginx-
  labels:
    appName: nginx
    car_id: "01234"
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
